Header header
# position projected on the GP in world coordinates
float64[] traj_x 
float64[] traj_y 
float64[] traj_z
# position projected on the GP in camera coordinates
float64[] traj_x_camera 
float64[] traj_y_camera 
float64[] traj_z_camera 
float64[] dir 	
float64 speed 	
int64 id
string uuid #Unique uuid5 (NAMESPACE_DNS) person id as string. Id is based on system time on start-up and id.
float64 score
